apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: namespacename
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
